### ISSUE TITLE
Creacion del scanner

### ISSUE THREAD

**Issue by chartre** [Angelnov/AplicacionBanco#1]
Tienes declarado un scanner dentro del bucle while, por lo que cada vez que se da una vuelta.
Hay que sacarlo fuera del bucle.

https://github.com/Angelnov/AplicacionBanco/blob/f595e85485b635bb2fe2588362fd5efeb04d9658/src/aplicacionbanco/AplicacionBanco.java#L147

**Comment by Angelnov** [comment]
yata
