### ISSUE TITLE
Lectura de integers

### ISSUE THREAD

**Issue by chartre** [Angelnov/AplicacionBanco#2]
Cuando usas nextInt, el scanner coge un numero, pero se deja fuera el salto de linea (porque no forma parte del numero) por eso muchas veces tienes que hacer un nextLine, para "coger" ese salto de linea.
El scanner trabaja de forma que lee caracteres hasta que se encuentra un caracter de salto de linea '\n', esa es la forma en la que sabe que se debe dejar de leer bytes del buffer. Pero cuando le pides nextInt, solo se preocupa de coger los bytes que hay en el buffer necesarios para rellenar un integer o hasta que un byte no represente un numero. En ese momento termina de coger bytes y, como despues de teclear has pulsado el enter, existe un caracter de salto de linea que se queda en el buffer porque no lo ha cogido la lectura anterior.
Usa nextLine y parsea a Integer. Yo lo he hecho y me funciona :)
https://github.com/Angelnov/AplicacionBanco/blob/f595e85485b635bb2fe2588362fd5efeb04d9658/src/aplicacionbanco/AplicacionBanco.java#L149

**Comment by Angelnov** [comment]
ya ta
